apiVersion: v1beta3
kind: Service
metadata: 
  labels: 
    name: rails
  name: rails
spec: 
  ports:
    - port: 80
      targetPort: 80
  selector: 
    name: rails
  createExternalLoadBalancer: true
